version: '3'
services:
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
