version: '3'
services:
  neo4j:
    image: neo4j:4.0.3
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_default__listen__address=0.0.0.0
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
  api:
    build: .
    depends_on:
      - neo4j
      - elastic
    ports:
      - "8000:8000"
